version: '3.7'

services:
  web:
    container_name: contacomigo_app
    build:
      context: ./
      dockerfile: Dockerfile-up
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=contacomigo_user
      - POSTGRES_PASSWORD=P@$$worD
      - POSTGRES_DB=contacomigo_dev

volumes:
  postgres_data: