version: '3.7'

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=contacomigo_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=contacomigo_dev

  redis:
    image: "redis:alpine"
    container_name: "contacomigo_redis"
#    command: redis-server --requirepass ConTaComigoApp
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master


volumes:
  postgres_data:
  redis_data: