# Generated by Django 2.2.11 on 2020-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='telephone_allowed',
            field=models.BooleanField(verbose_name='Telephone Allowed'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='telephone_allowed',
            field=models.BooleanField(verbose_name='Telephone Allowed'),
        ),
    ]
