# Generated by Django 2.2.11 on 2020-03-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_helprequestcancelingreason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequestCancelingReason',
        ),
        migrations.AlterField(
            model_name='helprequesthelpers',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='help.HelpingStatus'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequesthelpers',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='help.HelpingStatus'),
        ),
    ]
