# Generated by Django 2.2.11 on 2020-04-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("help", "0003_auto_20200329_2145")]

    operations = [
        migrations.CreateModel(
            name="HelpRequestCancelReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Description"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
