# Generated by Django 2.2.11 on 2020-04-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200411_2007'),
        ('help', '0005_auto_20200404_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='help_requests', to='app.UserAddress', verbose_name='Address where the help request is needed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.UserAddress', verbose_name='Address where the help request is needed'),
        ),
    ]
