# Generated by Django 2.2.11 on 2020-04-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Email status id')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Notification content')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=300, verbose_name='Sender')),
                ('recipient', models.TextField(verbose_name='Recipient')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='HTML content')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='notification.EmailStatus')),
            ],
        ),
    ]
