# Generated by Django 2.2.11 on 2020-04-19 13:06

import app.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import utils.models_validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('avatar', models.URLField(default='https://firebasestorage.googleapis.com/v0/b/conta-comigo-app-files.appspot.com/o/icon-conta-comigo.jpeg?alt=media&token=0094390a-0f27-4735-a0be-5926c5302b6e', verbose_name='Avatar')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='Super user')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.models_validations.validate_cpf], verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(max_length=14, validators=[utils.models_validations.validate_phone], verbose_name='Telefone')),
                ('is_phone_whatsapp', models.BooleanField(verbose_name='Telefone é whatsapp')),
                ('is_at_risk_group', models.BooleanField(verbose_name='É do grupo de risco')),
                ('live_alone', models.BooleanField(verbose_name='Mora sozinho')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalVariableType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Description')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborhoods', to='app.City', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('initials', models.CharField(max_length=2, unique=True, verbose_name='Initials')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Description')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_addresses', to='app.Neighborhood', verbose_name='Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(blank=True, editable=False, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('avatar', models.URLField(default='https://firebasestorage.googleapis.com/v0/b/conta-comigo-app-files.appspot.com/o/icon-conta-comigo.jpeg?alt=media&token=0094390a-0f27-4735-a0be-5926c5302b6e', verbose_name='Avatar')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='Super user')),
                ('cpf', models.CharField(db_index=True, max_length=11, validators=[utils.models_validations.validate_cpf], verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(max_length=14, validators=[utils.models_validations.validate_phone], verbose_name='Telefone')),
                ('is_phone_whatsapp', models.BooleanField(verbose_name='Telefone é whatsapp')),
                ('is_at_risk_group', models.BooleanField(verbose_name='É do grupo de risco')),
                ('live_alone', models.BooleanField(verbose_name='Mora sozinho')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Global variable value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='global_variables', to='app.GlobalVariableType', verbose_name='Global variable')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='app.State', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip code')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='app.Neighborhood', verbose_name='Neighborhood')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_query_name='user', to='app.UserAddress'),
        ),
    ]
