# Generated by Django 2.2.11 on 2020-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_city")]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress", models.CharField(max_length=250, verbose_name="Address")),
                (
                    "complement",
                    models.CharField(max_length=80, verbose_name="Complement"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
            ],
        )
    ]
