# Generated by Django 2.2.11 on 2020-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_address")]

    operations = [
        migrations.CreateModel(
            name="Zip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip", models.CharField(max_length=12, verbose_name="Zip code")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
            ],
        )
    ]
