# Generated by Django 2.2.11 on 2020-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0004_zip")]

    operations = [
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(max_length=150, verbose_name="Neighborhood"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
            ],
        )
    ]
