# Generated by Django 2.2.11 on 2020-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0008_auto_20200406_2249")]

    operations = [
        migrations.AlterField(
            model_name="globalvariable",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
