# Generated by Django 2.2.11 on 2020-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0011_auto_20200407_1450")]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="description",
            field=models.CharField(max_length=150, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="city",
            name="description",
            field=models.CharField(max_length=150, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="description",
            field=models.CharField(max_length=150, verbose_name="Description"),
        ),
    ]
