# Generated by Django 2.2.11 on 2020-04-08 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0013_auto_20200407_1542")]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cities",
                to="app.State",
                verbose_name="State",
            ),
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=150, verbose_name="Description"),
                ),
                ("zip_code", models.CharField(max_length=8, verbose_name="Zip code")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "city_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_addresses",
                        to="app.City",
                        verbose_name="City",
                    ),
                ),
                (
                    "neighborhood_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_addresses",
                        to="app.Neighborhood",
                        verbose_name="Neighborhood",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_addresses",
                        to="app.State",
                        verbose_name="State",
                    ),
                ),
            ],
        ),
    ]
