# Generated by Django 2.2.11 on 2020-04-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200408_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_query_name='user', to='app.UserAddress'),
        ),
    ]
