# Generated by Django 2.2.11 on 2020-04-10 20:07

import datetime
from django.db import migrations, models
import utils.models_validations


class Migration(migrations.Migration):

    dependencies = [("app", "0017_auto_20200408_0151")]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2020, 4, 10, 21, 4, 56, 768851),
                verbose_name="Data de nascimento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="cpf",
            field=models.CharField(
                default="00000000000",
                max_length=11,
                validators=[utils.models_validations.validate_cpf],
                verbose_name="CPF",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="is_at_risk_group",
            field=models.BooleanField(
                default=False, verbose_name="É do grupo de risco"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="is_phone_whatsapp",
            field=models.BooleanField(
                default=False, verbose_name="Telefone é whatsapp"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="live_alone",
            field=models.BooleanField(default=False, verbose_name="Mora sozinho"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="phone_number",
            field=models.CharField(
                default="+0000000000000",
                max_length=14,
                validators=[utils.models_validations.validate_phone],
                verbose_name="Telefone",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2020, 4, 10, 21, 5, 58, 934083),
                verbose_name="Data de nascimento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                default="00000000000",
                max_length=11,
                validators=[utils.models_validations.validate_cpf],
                verbose_name="CPF",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_at_risk_group",
            field=models.BooleanField(
                default=False, verbose_name="É do grupo de risco"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_whatsapp",
            field=models.BooleanField(
                default=False, verbose_name="Telefone é whatsapp"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="live_alone",
            field=models.BooleanField(default=False, verbose_name="Mora sozinho"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="+0000000000000",
                max_length=14,
                validators=[utils.models_validations.validate_phone],
                verbose_name="Telefone",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="images/%Y/%m/"),
        ),
    ]
