# Generated by Django 2.2.11 on 2020-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0018_auto_20200410_2107")]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="avatar",
            field=models.URLField(
                default="https://firebasestorage.googleapis.com/v0/b/conta-comigo-app-files.appspot.com/o/icon-conta-comigo.jpeg?alt=media&token=0094390a-0f27-4735-a0be-5926c5302b6e",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                default="https://firebasestorage.googleapis.com/v0/b/conta-comigo-app-files.appspot.com/o/icon-conta-comigo.jpeg?alt=media&token=0094390a-0f27-4735-a0be-5926c5302b6e",
                verbose_name="Avatar",
            ),
        ),
    ]
