# Generated by Django 2.2.11 on 2020-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_helps',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
